//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Front_page
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyWorkout
    {
        public int WorkoutId { get; set; }
        public string TypeofWorkout { get; set; }
        public string Duration { get; set; }
        public string CaloriesBurned { get; set; }
        public string Date { get; set; }
        public int UserId { get; set; }
    }
}
